### ISSUE TITLE
Proposal: adding a chain analysis warning in Wasabi wallet page

### ISSUE THREAD

**Issue by AnonymousMedusa** [bitcoin-dot-org/Bitcoin.org#4125]
Before pulling a request, I would like to talk about this and to read your opinions.  As I have said in the other [proposal](https://github.com/bitcoin-dot-org/Bitcoin.org/issues/4097), Wasabi wallet default coordinator is funding the operation of chain analysis company, which is something I believe the user should be aware of.

I believe that bitcoin.org should say below "This wallet lets you setup and use Tor ... your IP address." the following text:
```Funding of chain analysis
By default this wallet uses a central coordinator to coinjoin, which funds a chain analysis company.
```

This is just it.  Simple fact that the user must know. 

I think the following changes are sufficient, correct me otherwise:

1. In [en.yml](https://github.com/bitcoin-dot-org/Bitcoin.org/blob/c781429ded91ecc4202610309d34219c35ef367b/_translations/en.yml) addition of: ```checkpassfundingchainanalysis: "Funding of chain analysis"``` and
    ```checkpassfundingchainanalysistxt: "By default this wallet uses a central coordinator to coinjoin, which funds a chain analysis company."```
2. In [wasabi.md](https://github.com/bitcoin-dot-org/Bitcoin.org/blob/c781429ded91ecc4202610309d34219c35ef367b/_wallets/wasabi.md), addition of: ``fundingchainanalysis: "checkpassfundingchainanalysis"`` under ``privacynetwork: "checkpassprivacynetworksupporttorproxy"``
3. In [wallets.yaml](https://github.com/bitcoin-dot-org/Bitcoin.org/blob/c781429ded91ecc4202610309d34219c35ef367b/quality-assurance/schemas/wallets.yaml), addition of:

```
fundingchainanalysis:
                   description: Does the privacy-focused wallet fund the operation of a chain analysis company?
                   type: string
                   enum:
                     - checkpassfundingchainanalysis
 ```
